language: node_js
node_js:
- '8'
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_90389fc6c0b8_key -iv $encrypted_90389fc6c0b8_iv
  -in id_rsa.enc -out ~\/.ssh/id_rsa -d
