language: "node_js"
node_js:
  - '8'
branches:
  only:
  - master
before_script:
  - npm install
script:
  - npm test
addons:
  ssh_known_hosts:
    - 104.248.70.130

before_install:
  - openssl aes-256-cbc -K $encrypted_90389fc6c0b8_key -iv $encrypted_90389fc6c0b8_iv -in id_rsa.enc -out ~/.ssh/id_rsa -d
after_success:
  - chmod 600 ~/.ssh/id_rsa
  - ssh root@104.248.70.130 -o StrictHostKeyChecking=no 'npm install -g pm2 && cd ~/code/learn_ci && git pull origin master && npm install && npm run start'
