language: "node_js"
node_js:
  - "node"
  - '8'
branches:
  only:
  - master
install:
  - npm install
script: false
addons:
  ssh_known_hosts:
    - 104.248.70.130

before_install:
  - openssl aes-256-cbc -K $encrypted_90389fc6c0b8_key -iv $encrypted_90389fc6c0b8_iv -in id_rsa.enc -out ~/.ssh/id_rsa -d
after_success:
  - ssh root@104.248.70.130 -o StrictHostKeyChecking=no 'npm install -g pm2 && cd ~/code/learn_ci && git pull && npm install && npm run start'
